behaviors:
  AIAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory:
        memory_size: 256
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true

environment_parameters:
  room_difficulty:
    curriculum:
      - name: Easy
        completion_criteria:
          measure: progress
          behavior: AIAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 1.0
      - name: Medium
        completion_criteria:
          measure: progress
          behavior: AIAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 2.0
      - name: Hard
        completion_criteria:
          measure: progress
          behavior: AIAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.9
        value: 3.0